[package]
name = "moonbeam-relay-encoder"
version = '0.1.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
relay-encoder = { path = "../../primitives/relay-encoder/", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", default-features=false, branch = "joshy-np098"}
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }

[dev-dependencies]
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
kusama-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
westend-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
rococo-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "parity-scale-codec/std",
    "relay-encoder/std",
    "pallet-staking/std",
    "cumulus-primitives-core/std",
    "sp-runtime/std",
    "parity-scale-codec/std",
    "frame-system/std",
]
