[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'bin/utils/moonkey',
    'client/rpc-core/benchmark',
    'client/rpc/benchmark',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'
