[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'bin/utils/moonkey',
    'client/rpc-core/benchmark',
    'client/rpc/benchmark',
    'precompiles/utils/macro',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'

# Fix EVM tracing impact in block production pipeline.
[patch.crates-io]
evm = { git = "https://github.com/purestake/evm", branch = "jeremy-evm27-tracing-performance"}
evm-runtime = { git = "https://github.com/purestake/evm", branch = "jeremy-evm27-tracing-performance" }
evm-gasometer = { git = "https://github.com/purestake/evm", branch = "jeremy-evm27-tracing-performance" }
