[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonshadow',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'bin/utils/moonkey',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'

[patch.crates-io]
jsonrpc-core = { git = "https://github.com/purestake/jsonrpc", branch = "crystalin-testing-logs" }