[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonshadow',
    'runtime/moonbase',
    'runtime/relay_encoder',
    'node',
    'node/cli',
    'node/service',
    'bin/utils/moonkey',
    'pallets/xcm-wrapper',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'
