[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'pallets/migrations',
    'pallets/proxy-genesis-companion',
    'bin/utils/moonkey',
    'pallets/maintenance-mode',
    'precompiles/utils/macro',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'
