[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'pallets/migrations',
    'bin/utils/moonkey',
    'pallets/maintenance-mode',
    'precompiles/utils/macro',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'

# These overrides are necessary to support scale-info.
# Each one is associated with a PR in a dependency repo
[patch.crates-io]

# https://github.com/rust-blockchain/evm/pull/63
evm-core = { git = "https://github.com/purestake/evm", branch = "joshy-scale-info"}

# https://github.com/rust-blockchain/ethereum/pull/22
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info"}