[package]
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
name = 'relay-encoder'
repository = 'https://github.com/PureStake/moonbeam/'
version = '0.1.1'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", default-features = false, optional = true, features = ["derive"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = "0.4"
hex = { version = "0.4", default-features = false }
sha3 = { version = "0.8", default-features = false }
max-encoded-len = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8", features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }

cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", default-features=false, branch = "joshy-np098" }

[dev-dependencies]
hex = "0.4.3"

[features]
default = ["std"]
std = [
	"sp-std/std",
	"log/std",
	"parity-scale-codec/std",
	"serde/std",
	"hex/std",
	"sha3/std",
	"cumulus-primitives-core/std",
	"max-encoded-len/std",
	"pallet-staking/std",
	"sp-runtime/std"
]
