[package]
name = 'moonbeam'
description = 'Moonbeam Collator'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
version = '0.8.0-dev'
authors = ["PureStake"]
edition = '2018'

[[bin]]
name = 'moonbeam'
path = 'src/main.rs'

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
moonbeam-cli = { path = "cli" }
moonbeam-service = { path = "service" }
# required for benchmarking
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }

[dev-dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0"
assert_cmd = "0.12"
nix = "0.17"
tempfile = "3.2.0"
hex = "0.4.3"

[features]
default = []

test-spec = []

runtime-benchmarks = [
	"pallet-xcm/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"moonbeam-cli/runtime-benchmarks",
]
