[package]
name = "moonbeam-cli"
version = "0.11.3"
authors = ["PureStake"]
edition = "2018"

[dependencies]
hex = "0.4.3"
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.8"
parity-scale-codec = '2.2'

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", optional = true }
remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

cumulus-client-cli = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
cumulus-client-service = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
nimbus-primitives = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }

polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }

cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt", default-features = false }
rpc-client = { path = "../rpc-client" }
service = { package = "moonbeam-service", path = "../service", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

[features]
default = ["wasmtime"]
wasmtime = ["sc-cli/wasmtime"]
runtime-benchmarks = ["service/runtime-benchmarks"]
try-runtime = [
	"try-runtime-cli",
	"service/try-runtime",
]
