[package]
name = "moonbeam-vrf"
authors = [ "PureStake" ]
edition = "2018"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
futures = { version = "0.3.1", features = [ "compat" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
